#pragma once


#define KCTL_CODE(x) CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800 + x, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define KCE_READ_VIRTUAL_MEMORY KCTL_CODE(1) //读虚拟内存
#define KCE_WRITE_VIRTUAL_MEMORY KCTL_CODE(2) //写虚拟内存
#define KCE_PROTECT_PROCESS KCTL_CODE(3)//保护进程

typedef struct _READ_VIRTUAL_MEMORY_STRUCT
{
	ULONG Address;
	PVOID Response;
	SIZE_T Size;

}KCE_READ_VIRTUAL_MEMORY_STRUCT, *PKCE_READ_VIRTUAL_MEMORY_STRUCT;

typedef struct _WRITE_VIRTUAL_MEMORY_STRUCT
{
	ULONG Address;
	PVOID Value;
	SIZE_T Size;

}KCE_WRITE_VIRTUAL_MEMORY_STRUCT, *PKCE_WRITE_VIRTUAL_MEMORY_STRUCT;